// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (id,created_at, updated_at,user_id, key_hash,name,expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7)
RETURNING id, created_at, updated_at, user_id, key_hash, name, last_used_at, expires_at
`

type CreateApiKeyParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	KeyHash   string
	Name      string
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createApiKey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.KeyHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (id, created_at, updated_at, name, password_hash)
VALUES($1,$2,$3,$4,$5)
RETURNING id, created_at, updated_at, name, password_hash
`

type CreateUserWithPasswordParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPassword,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteApiKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteApiKey, arg.ID, arg.UserID)
	return err
}

const getApiKeyFromHash = `-- name: GetApiKeyFromHash :one
SELECT id, created_at, updated_at, user_id, key_hash, name, last_used_at, expires_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetApiKeyFromHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyFromHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getApiKeysForUsers = `-- name: GetApiKeysForUsers :many
SELECT id, created_at, updated_at, user_id, key_hash, name, last_used_at, expires_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetApiKeysForUsers(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getApiKeysForUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.KeyHash,
			&i.Name,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, created_at, updated_at, name, password_hash FROM users WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE api_keys SET last_used_at = $1 WHERE id = $2
`

type UpdateApiKeyLastUsedParams struct {
	LastUsedAt sql.NullTime
	ID         uuid.UUID
}

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, arg UpdateApiKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateApiKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1 , updated_at = $2
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    time.Time
	ID           uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
