// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id,created_at, updated_at,title, url, description, published_at, feed_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, feeds.name AS feed_name 
FROM posts
INNER JOIN feeds ON posts.feed_id = feeds.id
INNER JOIN feed_follows ON feeds.id = feed_follows.feed_id
WHERE feed_follows.user_id = $1
ORDER BY posts.published_at DESC
LIMIT $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetPostsForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
	FeedName    string
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsForUserSorted = `-- name: GetPostsForUserSorted :many
SELECT 
    p.id, p.created_at, p.updated_at, p.title, p.url,
    p.description, p.published_at, p.feed_id,
    f.name AS feed_name
FROM posts p
JOIN feed_follows ff ON p.feed_id = ff.feed_id
JOIN feeds f ON p.feed_id = f.id
WHERE ff.user_id = $1
  AND ($3 = '' OR f.name ILIKE '%' || $3 || '%')
ORDER BY
    -- Title-based sorting (text)
    CASE 
        WHEN $4 = 'title_asc'  THEN p.title
        WHEN $4 = 'title_desc' THEN p.title
        ELSE NULL
    END
    --
    , CASE 
        WHEN $4 = 'title_asc' THEN 1 
        WHEN $4 = 'title_desc' THEN -1 
        ELSE 0 
    END
    --
    -- Timestamp-based sorting (created/published)
    , CASE 
        WHEN $4 = 'created_at_asc'  THEN p.created_at
        WHEN $4 = 'created_at_desc' THEN p.created_at
        WHEN $4 = 'published_at_asc' THEN p.published_at
        WHEN $4 = 'published_at_desc' THEN p.published_at
        ELSE NULL
    END
    --
    , CASE 
        WHEN $4 LIKE '%_asc' THEN 1 
        WHEN $4 LIKE '%_desc' THEN -1 
        ELSE 0 
    END
LIMIT $2
OFFSET $5
`

type GetPostsForUserSortedParams struct {
	UserID  uuid.UUID
	Limit   int32
	Column3 interface{}
	Column4 interface{}
	Offset  int32
}

type GetPostsForUserSortedRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
	FeedName    string
}

func (q *Queries) GetPostsForUserSorted(ctx context.Context, arg GetPostsForUserSortedParams) ([]GetPostsForUserSortedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUserSorted,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserSortedRow
	for rows.Next() {
		var i GetPostsForUserSortedRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
