// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tiers.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const canUserAddFeed = `-- name: CanUserAddFeed :one
SELECT 
    CASE 
        WHEN st.max_feeds IS NULL THEN true
                WHEN (SELECT COUNT(*) FROM feed_follows WHERE feed_follows.user_id = $1) < st.max_feeds THEN true
        ELSE false
    END as can_add
FROM users u
LEFT JOIN users_subscriptions us ON u.id = us.user_id 
    AND us.status IN ('active', 'trialing')
LEFT JOIN subscription_tiers st ON us.tier_id = st.id
WHERE u.id = $1
ORDER BY us.created_at DESC
LIMIT 1
`

func (q *Queries) CanUserAddFeed(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, canUserAddFeed, userID)
	var can_add bool
	err := row.Scan(&can_add)
	return can_add, err
}

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE users_subscriptions
SET 
    status = 'canceled',
    updated_at = $2
WHERE id = $1
`

type CancelSubscriptionParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, cancelSubscription, arg.ID, arg.UpdatedAt)
	return err
}

const checkUserHasFeature = `-- name: CheckUserHasFeature :one

SELECT 
    CASE 
        WHEN us.id IS NULL THEN false
        WHEN st.features->$2 IS NULL THEN false
        WHEN (st.features->>$2)::boolean = true THEN true
        ELSE false
    END as has_feature
FROM users u
LEFT JOIN users_subscriptions us ON u.id = us.user_id 
    AND us.status IN ('active', 'trialing')
LEFT JOIN subscription_tiers st ON us.tier_id = st.id
WHERE u.id = $1
ORDER BY us.created_at DESC
LIMIT 1
`

type CheckUserHasFeatureParams struct {
	ID       uuid.UUID
	Features json.RawMessage
}

// ==========================================
// SUBSCRIPTION CHECKS
// ==========================================
func (q *Queries) CheckUserHasFeature(ctx context.Context, arg CheckUserHasFeatureParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserHasFeature, arg.ID, arg.Features)
	var has_feature bool
	err := row.Scan(&has_feature)
	return has_feature, err
}

const convertTrialToActive = `-- name: ConvertTrialToActive :exec
UPDATE users_subscriptions
SET 
    status = 'active',
    stripe_subscription_id = $2,
    updated_at = $3
WHERE id = $1
`

type ConvertTrialToActiveParams struct {
	ID                   uuid.UUID
	StripeSubscriptionID sql.NullString
	UpdatedAt            time.Time
}

func (q *Queries) ConvertTrialToActive(ctx context.Context, arg ConvertTrialToActiveParams) error {
	_, err := q.db.ExecContext(ctx, convertTrialToActive, arg.ID, arg.StripeSubscriptionID, arg.UpdatedAt)
	return err
}

const countUserFeeds = `-- name: CountUserFeeds :one

SELECT COUNT(*) FROM feed_follows
WHERE user_id = $1
`

// ==========================================
// USAGE LIMITS & COUNTS
// ==========================================
func (q *Queries) CountUserFeeds(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserFeeds, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserPosts = `-- name: CountUserPosts :one
SELECT COUNT(*) 
FROM posts p
JOIN feed_follows ff ON p.feed_id = ff.feed_id
WHERE ff.user_id = $1
`

func (q *Queries) CountUserPosts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPosts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (
    id,
    user_id,
    subscription_id,
    amount_cents,
    currency,
    status,
    stripe_payment_intent_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, subscription_id, amount_cents, currency, status, stripe_payment_intent_id, created_at
`

type CreatePaymentParams struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	SubscriptionID        uuid.NullUUID
	AmountCents           int32
	Currency              string
	Status                string
	StripePaymentIntentID sql.NullString
	CreatedAt             time.Time
}

// ==========================================
// PAYMENTS
// ==========================================
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.UserID,
		arg.SubscriptionID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.StripePaymentIntentID,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :exec

UPDATE payments
SET status = 'refunded'
WHERE id = $1
`

// ==========================================
// REFUNDS
// ==========================================
func (q *Queries) CreateRefund(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createRefund, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO users_subscriptions (
    id,
    user_id,
    tier_id,
    status,
    current_period_start,
    current_period_end,
    stripe_customer_id,
    stripe_subscription_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email
`

type CreateSubscriptionParams struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TierID               uuid.UUID
	Status               string
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.TierID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtEndPeriod,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO subscription_tiers (
    id,
    name,
    price_cents,
    max_feeds,
    max_posts,
    features,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, price_cents, max_feeds, max_posts, features, created_at
`

type CreateTierParams struct {
	ID         uuid.UUID
	Name       string
	PriceCents int32
	MaxFeeds   int32
	MaxPosts   sql.NullInt32
	Features   json.RawMessage
	CreatedAt  time.Time
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (SubscriptionTier, error) {
	row := q.db.QueryRowContext(ctx, createTier,
		arg.ID,
		arg.Name,
		arg.PriceCents,
		arg.MaxFeeds,
		arg.MaxPosts,
		arg.Features,
		arg.CreatedAt,
	)
	var i SubscriptionTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.MaxFeeds,
		&i.MaxPosts,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const createUsageMetric = `-- name: CreateUsageMetric :one

INSERT INTO usage_metrics (
    id,
    user_id,
    metric_type,
    count,
    period_start,
    period_end,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, metric_type, count, period_start, period_end, created_at
`

type CreateUsageMetricParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	MetricType  string
	Count       int32
	PeriodStart time.Time
	PeriodEnd   time.Time
	CreatedAt   time.Time
}

// ==========================================
// USAGE METRICS
// ==========================================
func (q *Queries) CreateUsageMetric(ctx context.Context, arg CreateUsageMetricParams) (UsageMetric, error) {
	row := q.db.QueryRowContext(ctx, createUsageMetric,
		arg.ID,
		arg.UserID,
		arg.MetricType,
		arg.Count,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CreatedAt,
	)
	var i UsageMetric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MetricType,
		&i.Count,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIUsageThisMonth = `-- name: GetAPIUsageThisMonth :one
SELECT COALESCE(count, 0) as count
FROM usage_metrics
WHERE user_id = $1
AND metric_type = 'api_calls'
AND period_start >= date_trunc('month', NOW())
AND period_end < date_trunc('month', NOW() + interval '1 month')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetAPIUsageThisMonth(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAPIUsageThisMonth, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getActiveSubscriptionsCount = `-- name: GetActiveSubscriptionsCount :one

SELECT COUNT(*) as count
FROM users_subscriptions
WHERE status IN ('active', 'trialing')
`

// ==========================================
// ANALYTICS & REPORTING
// ==========================================
func (q *Queries) GetActiveSubscriptionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllTiers = `-- name: GetAllTiers :many

SELECT id, name, price_cents, max_feeds, max_posts, features, created_at FROM subscription_tiers
ORDER BY price_cents ASC
`

// ==========================================
// SUBSCRIPTION TIERS
// ==========================================
func (q *Queries) GetAllTiers(ctx context.Context) ([]SubscriptionTier, error) {
	rows, err := q.db.QueryContext(ctx, getAllTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionTier
	for rows.Next() {
		var i SubscriptionTier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.MaxFeeds,
			&i.MaxPosts,
			&i.Features,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChurnedSubscriptionsThisMonth = `-- name: GetChurnedSubscriptionsThisMonth :one
SELECT COUNT(*) as count
FROM users_subscriptions
WHERE status = 'canceled'
AND updated_at >= date_trunc('month', NOW())
`

func (q *Queries) GetChurnedSubscriptionsThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChurnedSubscriptionsThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentPeriodUsage = `-- name: GetCurrentPeriodUsage :one
SELECT id, user_id, metric_type, count, period_start, period_end, created_at FROM usage_metrics
WHERE user_id = $1
AND metric_type = $2
AND period_end > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetCurrentPeriodUsageParams struct {
	UserID     uuid.UUID
	MetricType string
}

func (q *Queries) GetCurrentPeriodUsage(ctx context.Context, arg GetCurrentPeriodUsageParams) (UsageMetric, error) {
	row := q.db.QueryRowContext(ctx, getCurrentPeriodUsage, arg.UserID, arg.MetricType)
	var i UsageMetric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MetricType,
		&i.Count,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiringTrials = `-- name: GetExpiringTrials :many
SELECT us.id, us.user_id, us.tier_id, us.status, us.current_period_start, us.current_period_end, us.cancel_at_end_period, us.stripe_customer_id, us.stripe_subscription_id, us.created_at, us.updated_at, us.email, u.name as user_name, u.email as user_email
FROM users_subscriptions us
JOIN users u ON us.user_id = u.id
WHERE us.status = 'trialing'
AND us.current_period_end <= NOW() + interval '3 days'
AND us.current_period_end > NOW()
`

type GetExpiringTrialsRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TierID               uuid.UUID
	Status               string
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	CancelAtEndPeriod    sql.NullBool
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Email                sql.NullString
	UserName             string
	UserEmail            sql.NullString
}

func (q *Queries) GetExpiringTrials(ctx context.Context) ([]GetExpiringTrialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiringTrials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiringTrialsRow
	for rows.Next() {
		var i GetExpiringTrialsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtEndPeriod,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedPayments = `-- name: GetFailedPayments :many

SELECT p.id, p.user_id, p.subscription_id, p.amount_cents, p.currency, p.status, p.stripe_payment_intent_id, p.created_at, u.name as user_name, u.email as user_email
FROM payments p
JOIN users u ON p.user_id = u.id
WHERE p.status = 'failed'
AND p.created_at >= $1
ORDER BY p.created_at DESC
`

type GetFailedPaymentsRow struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	SubscriptionID        uuid.NullUUID
	AmountCents           int32
	Currency              string
	Status                string
	StripePaymentIntentID sql.NullString
	CreatedAt             time.Time
	UserName              string
	UserEmail             sql.NullString
}

// ==========================================
// FAILED PAYMENT HANDLING
// ==========================================
func (q *Queries) GetFailedPayments(ctx context.Context, createdAt time.Time) ([]GetFailedPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFailedPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedPaymentsRow
	for rows.Next() {
		var i GetFailedPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyRecurringRevenue = `-- name: GetMonthlyRecurringRevenue :one
SELECT COALESCE(SUM(st.price_cents), 0) as mrr_cents
FROM users_subscriptions us
JOIN subscription_tiers st ON us.tier_id = st.id
WHERE us.status IN ('active', 'trialing')
`

func (q *Queries) GetMonthlyRecurringRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyRecurringRevenue)
	var mrr_cents interface{}
	err := row.Scan(&mrr_cents)
	return mrr_cents, err
}

const getNewSubscriptionsThisMonth = `-- name: GetNewSubscriptionsThisMonth :one
SELECT COUNT(*) as count
FROM users_subscriptions
WHERE status IN ('active', 'trialing')
AND created_at >= date_trunc('month', NOW())
`

func (q *Queries) GetNewSubscriptionsThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNewSubscriptionsThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPastDueSubscriptions = `-- name: GetPastDueSubscriptions :many
SELECT us.id, us.user_id, us.tier_id, us.status, us.current_period_start, us.current_period_end, us.cancel_at_end_period, us.stripe_customer_id, us.stripe_subscription_id, us.created_at, us.updated_at, us.email, u.name as user_name, u.email as user_email
FROM users_subscriptions us
JOIN users u ON us.user_id = u.id
WHERE us.status = 'past_due'
`

type GetPastDueSubscriptionsRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TierID               uuid.UUID
	Status               string
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	CancelAtEndPeriod    sql.NullBool
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Email                sql.NullString
	UserName             string
	UserEmail            sql.NullString
}

func (q *Queries) GetPastDueSubscriptions(ctx context.Context) ([]GetPastDueSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPastDueSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastDueSubscriptionsRow
	for rows.Next() {
		var i GetPastDueSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtEndPeriod,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByStripeID = `-- name: GetPaymentByStripeID :one
SELECT id, user_id, subscription_id, amount_cents, currency, status, stripe_payment_intent_id, created_at FROM payments
WHERE stripe_payment_intent_id = $1
`

func (q *Queries) GetPaymentByStripeID(ctx context.Context, stripePaymentIntentID sql.NullString) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByStripeID, stripePaymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.StripePaymentIntentID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentsBySubscription = `-- name: GetPaymentsBySubscription :many
SELECT id, user_id, subscription_id, amount_cents, currency, status, stripe_payment_intent_id, created_at FROM payments
WHERE subscription_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsBySubscription(ctx context.Context, subscriptionID uuid.NullUUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDowngrades = `-- name: GetPendingDowngrades :many
SELECT us.id, us.user_id, us.tier_id, us.status, us.current_period_start, us.current_period_end, us.cancel_at_end_period, us.stripe_customer_id, us.stripe_subscription_id, us.created_at, us.updated_at, us.email, st.name as new_tier_name
FROM users_subscriptions us
JOIN subscription_tiers st ON us.tier_id = st.id
WHERE us.current_period_end <= NOW()
AND us.cancel_at_period_end = false
`

type GetPendingDowngradesRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TierID               uuid.UUID
	Status               string
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	CancelAtEndPeriod    sql.NullBool
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Email                sql.NullString
	NewTierName          string
}

func (q *Queries) GetPendingDowngrades(ctx context.Context) ([]GetPendingDowngradesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingDowngrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingDowngradesRow
	for rows.Next() {
		var i GetPendingDowngradesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtEndPeriod,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.NewTierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefundedPayments = `-- name: GetRefundedPayments :many
SELECT p.id, p.user_id, p.subscription_id, p.amount_cents, p.currency, p.status, p.stripe_payment_intent_id, p.created_at, u.name as user_name
FROM payments p
JOIN users u ON p.user_id = u.id
WHERE p.status = 'refunded'
AND p.created_at >= $1
ORDER BY p.created_at DESC
`

type GetRefundedPaymentsRow struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	SubscriptionID        uuid.NullUUID
	AmountCents           int32
	Currency              string
	Status                string
	StripePaymentIntentID sql.NullString
	CreatedAt             time.Time
	UserName              string
}

func (q *Queries) GetRefundedPayments(ctx context.Context, createdAt time.Time) ([]GetRefundedPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRefundedPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefundedPaymentsRow
	for rows.Next() {
		var i GetRefundedPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByMonth = `-- name: GetRevenueByMonth :many
SELECT 
    date_trunc('month', created_at) as month,
    SUM(amount_cents) as revenue_cents,
    COUNT(*) as payment_count
FROM payments
WHERE status = 'succeeded'
AND created_at >= $1
GROUP BY date_trunc('month', created_at)
ORDER BY month DESC
`

type GetRevenueByMonthRow struct {
	Month        int64
	RevenueCents int64
	PaymentCount int64
}

func (q *Queries) GetRevenueByMonth(ctx context.Context, createdAt time.Time) ([]GetRevenueByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueByMonth, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByMonthRow
	for rows.Next() {
		var i GetRevenueByMonthRow
		if err := rows.Scan(&i.Month, &i.RevenueCents, &i.PaymentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email FROM users_subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtEndPeriod,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email FROM users_subscriptions
WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID sql.NullString) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtEndPeriod,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getSubscriptionsByTier = `-- name: GetSubscriptionsByTier :many
SELECT 
    st.name as tier_name,
    COUNT(*) as count,
    SUM(st.price_cents) as total_revenue_cents
FROM users_subscriptions us
JOIN subscription_tiers st ON us.tier_id = st.id
WHERE us.status IN ('active', 'trialing')
GROUP BY st.name, st.price_cents
ORDER BY st.price_cents DESC
`

type GetSubscriptionsByTierRow struct {
	TierName          string
	Count             int64
	TotalRevenueCents int64
}

func (q *Queries) GetSubscriptionsByTier(ctx context.Context) ([]GetSubscriptionsByTierRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsByTierRow
	for rows.Next() {
		var i GetSubscriptionsByTierRow
		if err := rows.Scan(&i.TierName, &i.Count, &i.TotalRevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuccessfulPaymentsTotal = `-- name: GetSuccessfulPaymentsTotal :one
SELECT COALESCE(SUM(amount_cents), 0) as total
FROM payments
WHERE user_id = $1
AND status = 'succeeded'
`

func (q *Queries) GetSuccessfulPaymentsTotal(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getSuccessfulPaymentsTotal, userID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTierByID = `-- name: GetTierByID :one
SELECT id, name, price_cents, max_feeds, max_posts, features, created_at FROM subscription_tiers
WHERE id = $1
`

func (q *Queries) GetTierByID(ctx context.Context, id uuid.UUID) (SubscriptionTier, error) {
	row := q.db.QueryRowContext(ctx, getTierByID, id)
	var i SubscriptionTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.MaxFeeds,
		&i.MaxPosts,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const getTierByName = `-- name: GetTierByName :one
SELECT id, name, price_cents, max_feeds, max_posts, features, created_at FROM subscription_tiers
WHERE name = $1
`

func (q *Queries) GetTierByName(ctx context.Context, name string) (SubscriptionTier, error) {
	row := q.db.QueryRowContext(ctx, getTierByName, name)
	var i SubscriptionTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.MaxFeeds,
		&i.MaxPosts,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const getTopPayingUsers = `-- name: GetTopPayingUsers :many
SELECT 
    u.id,
    u.name,
    SUM(p.amount_cents) as total_paid_cents,
    COUNT(p.id) as payment_count
FROM users u
JOIN payments p ON u.id = p.user_id
WHERE p.status = 'succeeded'
GROUP BY u.id, u.name
ORDER BY total_paid_cents DESC
LIMIT $1
`

type GetTopPayingUsersRow struct {
	ID             uuid.UUID
	Name           string
	TotalPaidCents int64
	PaymentCount   int64
}

func (q *Queries) GetTopPayingUsers(ctx context.Context, limit int32) ([]GetTopPayingUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopPayingUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPayingUsersRow
	for rows.Next() {
		var i GetTopPayingUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalPaidCents,
			&i.PaymentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageHistory = `-- name: GetUsageHistory :many
SELECT id, user_id, metric_type, count, period_start, period_end, created_at FROM usage_metrics
WHERE user_id = $1
AND metric_type = $2
ORDER BY period_start DESC
LIMIT $3
`

type GetUsageHistoryParams struct {
	UserID     uuid.UUID
	MetricType string
	Limit      int32
}

func (q *Queries) GetUsageHistory(ctx context.Context, arg GetUsageHistoryParams) ([]UsageMetric, error) {
	rows, err := q.db.QueryContext(ctx, getUsageHistory, arg.UserID, arg.MetricType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageMetric
	for rows.Next() {
		var i UsageMetric
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MetricType,
			&i.Count,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT u.id, u.created_at, u.updated_at, u.name, u.password_hash, u.email 
FROM users u
JOIN users_subscriptions us ON u.id = us.user_id
WHERE us.stripe_customer_id = $1
LIMIT 1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PasswordHash,
		&i.Email,
	)
	return i, err
}

const getUserPayments = `-- name: GetUserPayments :many
SELECT id, user_id, subscription_id, amount_cents, currency, status, stripe_payment_intent_id, created_at FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserPaymentsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetUserPayments(ctx context.Context, arg GetUserPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getUserPayments, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.StripePaymentIntentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubscription = `-- name: GetUserSubscription :one

SELECT id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email FROM users_subscriptions
WHERE user_id = $1
AND status IN ('active', 'trialing')
ORDER BY created_at DESC
LIMIT 1
`

// ==========================================
// USER SUBSCRIPTIONS
// ==========================================
func (q *Queries) GetUserSubscription(ctx context.Context, userID uuid.UUID) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserSubscription, userID)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtEndPeriod,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserSubscriptionHistory = `-- name: GetUserSubscriptionHistory :many
SELECT id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email FROM users_subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserSubscriptionHistory(ctx context.Context, userID uuid.UUID) ([]UsersSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptionHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersSubscription
	for rows.Next() {
		var i UsersSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TierID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtEndPeriod,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTierLimits = `-- name: GetUserTierLimits :one
SELECT 
    COALESCE(st.max_feeds, 2147483647) as max_feeds,
    COALESCE(st.max_posts, 2147483647) as max_posts,
    st.features
FROM users u
LEFT JOIN users_subscriptions us ON u.id = us.user_id 
    AND us.status IN ('active', 'trialing')
LEFT JOIN subscription_tiers st ON us.tier_id = st.id
WHERE u.id = $1
ORDER BY us.created_at DESC
LIMIT 1
`

type GetUserTierLimitsRow struct {
	MaxFeeds int32
	MaxPosts int32
	Features pqtype.NullRawMessage
}

func (q *Queries) GetUserTierLimits(ctx context.Context, id uuid.UUID) (GetUserTierLimitsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTierLimits, id)
	var i GetUserTierLimitsRow
	err := row.Scan(&i.MaxFeeds, &i.MaxPosts, &i.Features)
	return i, err
}

const incrementAPIUsage = `-- name: IncrementAPIUsage :exec
INSERT INTO usage_metrics (
    id,
    user_id,
    metric_type,
    count,
    period_start,
    period_end,
    created_at
) VALUES (
    gen_random_uuid(),
    $1,
    'api_calls',
    1,
    date_trunc('month', NOW()),
    date_trunc('month', NOW() + interval '1 month'),
    NOW()
)
ON CONFLICT (user_id, metric_type, period_start)
DO UPDATE SET count = usage_metrics.count + 1
`

func (q *Queries) IncrementAPIUsage(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementAPIUsage, userID)
	return err
}

const incrementUsageMetric = `-- name: IncrementUsageMetric :exec
UPDATE usage_metrics
SET count = count + 1
WHERE id = $1
`

func (q *Queries) IncrementUsageMetric(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementUsageMetric, id)
	return err
}

const markSubscriptionPastDue = `-- name: MarkSubscriptionPastDue :exec
UPDATE users_subscriptions
SET 
    status = 'past_due',
    updated_at = $2
WHERE id = $1
`

type MarkSubscriptionPastDueParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) MarkSubscriptionPastDue(ctx context.Context, arg MarkSubscriptionPastDueParams) error {
	_, err := q.db.ExecContext(ctx, markSubscriptionPastDue, arg.ID, arg.UpdatedAt)
	return err
}

const scheduleDowngrade = `-- name: ScheduleDowngrade :exec

UPDATE users_subscriptions
SET 
    tier_id = $2,
    cancel_at_period_end = false,
    updated_at = $3
WHERE id = $1
`

type ScheduleDowngradeParams struct {
	ID        uuid.UUID
	TierID    uuid.UUID
	UpdatedAt time.Time
}

// ==========================================
// DOWNGRADE/UPGRADE MANAGEMENT
// ==========================================
func (q *Queries) ScheduleDowngrade(ctx context.Context, arg ScheduleDowngradeParams) error {
	_, err := q.db.ExecContext(ctx, scheduleDowngrade, arg.ID, arg.TierID, arg.UpdatedAt)
	return err
}

const startTrial = `-- name: StartTrial :one

INSERT INTO users_subscriptions (
    id,
    user_id,
    tier_id,
    status,
    current_period_start,
    current_period_end,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    'trialing',
    NOW(),
    NOW() + interval '14 days',
    NOW(),
    NOW()
)
RETURNING id, user_id, tier_id, status, current_period_start, current_period_end, cancel_at_end_period, stripe_customer_id, stripe_subscription_id, created_at, updated_at, email
`

type StartTrialParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	TierID uuid.UUID
}

// ==========================================
// TRIAL MANAGEMENT
// ==========================================
func (q *Queries) StartTrial(ctx context.Context, arg StartTrialParams) (UsersSubscription, error) {
	row := q.db.QueryRowContext(ctx, startTrial, arg.ID, arg.UserID, arg.TierID)
	var i UsersSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TierID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtEndPeriod,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = $2
WHERE id = $1
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	return err
}

const updateSubscriptionCancelation = `-- name: UpdateSubscriptionCancelation :exec
UPDATE users_subscriptions
SET 
    cancel_at_end_period= $2,
    updated_at = $3
WHERE id = $1
`

type UpdateSubscriptionCancelationParams struct {
	ID                uuid.UUID
	CancelAtEndPeriod sql.NullBool
	UpdatedAt         time.Time
}

func (q *Queries) UpdateSubscriptionCancelation(ctx context.Context, arg UpdateSubscriptionCancelationParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionCancelation, arg.ID, arg.CancelAtEndPeriod, arg.UpdatedAt)
	return err
}

const updateSubscriptionPeriod = `-- name: UpdateSubscriptionPeriod :exec
UPDATE users_subscriptions
SET 
    current_period_start = $2,
    current_period_end = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateSubscriptionPeriodParams struct {
	ID                 uuid.UUID
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpdateSubscriptionPeriod(ctx context.Context, arg UpdateSubscriptionPeriodParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionPeriod,
		arg.ID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.UpdatedAt,
	)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE users_subscriptions
SET 
    status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateSubscriptionTier = `-- name: UpdateSubscriptionTier :exec
UPDATE users_subscriptions
SET 
    tier_id = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateSubscriptionTierParams struct {
	ID        uuid.UUID
	TierID    uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) UpdateSubscriptionTier(ctx context.Context, arg UpdateSubscriptionTierParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionTier, arg.ID, arg.TierID, arg.UpdatedAt)
	return err
}

const updateTier = `-- name: UpdateTier :one
UPDATE subscription_tiers
SET 
    price_cents = $2,
    max_feeds = $3,
    max_posts = $4,
    features = $5
WHERE id = $1
RETURNING id, name, price_cents, max_feeds, max_posts, features, created_at
`

type UpdateTierParams struct {
	ID         uuid.UUID
	PriceCents int32
	MaxFeeds   int32
	MaxPosts   sql.NullInt32
	Features   json.RawMessage
}

func (q *Queries) UpdateTier(ctx context.Context, arg UpdateTierParams) (SubscriptionTier, error) {
	row := q.db.QueryRowContext(ctx, updateTier,
		arg.ID,
		arg.PriceCents,
		arg.MaxFeeds,
		arg.MaxPosts,
		arg.Features,
	)
	var i SubscriptionTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.MaxFeeds,
		&i.MaxPosts,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserStripeCustomer = `-- name: UpdateUserStripeCustomer :exec

UPDATE users_subscriptions
SET 
    stripe_customer_id = $2,
    updated_at = $3
WHERE user_id = $1
`

type UpdateUserStripeCustomerParams struct {
	UserID           uuid.UUID
	StripeCustomerID sql.NullString
	UpdatedAt        time.Time
}

// ==========================================
// STRIPE CUSTOMER MANAGEMENT
// ==========================================
func (q *Queries) UpdateUserStripeCustomer(ctx context.Context, arg UpdateUserStripeCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStripeCustomer, arg.UserID, arg.StripeCustomerID, arg.UpdatedAt)
	return err
}

const userTestTiers = `-- name: UserTestTiers :one
INSERT INTO subscription_tiers(name, price_cents, max_feeds, max_posts, features) VALUES
('free', 0, 5, 100, '{"api_access": false, "tui_access": false}'),
('pro', 900, 50, NULL, '{"api_access": true, "tui_access": true, "email_support": true}'),
('team', 2900, 200, NULL, '{"api_access": true, "tui_access": true, "multi_user": true, "webhooks": true}'),
('enterprise', 9900, NULL, NULL, '{"api_access": true, "tui_access": true, "multi_user": true, "webhooks": true, "sla": true}')
RETURNING id, name, price_cents, max_feeds, max_posts, features, created_at
`

func (q *Queries) UserTestTiers(ctx context.Context) (SubscriptionTier, error) {
	row := q.db.QueryRowContext(ctx, userTestTiers)
	var i SubscriptionTier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.MaxFeeds,
		&i.MaxPosts,
		&i.Features,
		&i.CreatedAt,
	)
	return i, err
}
