name: cd

on:
    push:
        branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v6
            
            # Authenticate with GCP
            - name: Authenticate to Google cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            # Set up gcloud CLI
            - name: Set up cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            # Build and push image using Cloud Build
            - name: Build and push image
              run: |
                gcloud builds submit \
                  --tag us-central1-docker.pkg.dev/abstract-arbor-486909-f5/bloggator-repo/api-service:${{ github.sha }} \
                  .

            # Deploy to Cloud Run
            - name: Deploy to Cloud Run
              run: |
                gcloud run deploy api-service \
                  --image us-central1-docker.pkg.dev/abstract-arbor-486909-f5/bloggator-repo/api-service:${{ github.sha }} \
                  --region us-central1 \
                  --platform managed \
                  --set-env-vars "GATOR_CONFIG_FILE=/app/config/gator-config.json"
                  --allow-unauthenticated 
                  --quiet
